# Generated by Django 6.1.1 on 2026-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('phone', models.IntegerField(max_length=15, verbose_name='Phone number')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-first_name'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='clist_conta_first_n_938dad_idx')],
            },
        ),
    ]
